version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/portfolio-app

hooks:
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: ec2-user
      permissions: +x  # Add executable permissions

  Install:
    - location: scripts/install-packages.sh
      timeout: 600
      runas: ec2-user
      permissions: +x  # Add executable permissions

  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 300
      runas: ec2-user
      permissions: +x  # Add executable permissions

permissions:
  - object: /var/www/html/portfolio-app
    pattern: "**/*"
    owner: ec2-user
    group: ec2-user
    mode: 766
  - object: /var/www/html/portfolio-app
    pattern: "**/*.sh"
    owner: ec2-user
    group: ec2-user
    mode: 755
